language: node_js
script:
  - npm build
node_js:
  - "iojs"
  - "7"
after_script: 
 NODE_ENV=test ./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha --report  lcovonly -- -- -u exports -R ./out/tests/**/*.js && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage